# Compile stage
FROM golang:1.24-bullseye AS build-env

WORKDIR /dockerdev

# Copy go mod and sum files first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Install swag CLI
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Generate Swagger docs
RUN /go/bin/swag init

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Build the binary with debug flags
RUN go build -gcflags="all=-N -l" -o /server

# Final stage
FROM debian:bullseye

EXPOSE 8000 40000

WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /server /

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]