#!/bin/sh
MY_MESSAGE="Hello World"
echo $MY_MESSAGE

MY_MESSAGE="Hello World"
MY_SHORT_MESSAGE=hi
MY_NUMBER=1
MY_PI=3.142
MY_OTHER_PI="3.142"
MY_MIXED=123abc
MY_INT=1

echo $MY_PI + 1
echo $MY_OTHER_PI + 1
expr $MY_INT + 1